stages:
  - test
  - build
  - deploy

variables:
  DOCKER_IMAGE: hibamhada/prix-immo-ai

test:unit:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install -r app/requirements.txt
  script:
    - cd app
    - python -m pytest tests/ -v --tb=short
  only:
    - main
    - merge_requests

build:docker:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  script:
    - docker build -t $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA .
    - docker build -t $DOCKER_IMAGE:latest .
    - docker push $DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_IMAGE:latest
  only:
    - main

deploy:kubernetes:
  stage: deploy
  image:
    name: bitnami/kubectl:latest
    entrypoint: [""]
  before_script:
    - kubectl version --client
  script:
    - kubectl --kubeconfig=$KUBECONFIG_CONTENT --insecure-skip-tls-verify get nodes
    - kubectl --kubeconfig=$KUBECONFIG_CONTENT --insecure-skip-tls-verify set image deployment/flask-app flask-container=$DOCKER_IMAGE:$CI_COMMIT_SHORT_SHA
    - kubectl --kubeconfig=$KUBECONFIG_CONTENT --insecure-skip-tls-verify rollout status deployment/flask-app --timeout=120s
  environment:
    name: production
    url: http://51.11.241.115:30080
  only:
    - main